pipeline {

    agent any

    environment {
        def prename = 'no'
        def lastname = 'name'
    }
    
    stages {
        stage('Assign variables') {
            steps {
                script {
                    
                    def valuesFromFile = readFile '<path to your values file>'
                    def lines = valuesFromFile.split('\n')
                    def keyValueMap = [:]
        
                    lines.each { line ->
                        def keyValue = line.split(':')
                        if(keyValue.size() == 2){
                            def key = keyValue[0].trim()
                            def value = keyValue[1].trim()
                            keyValueMap[key] = value
                        }
                    }
                    prename = keyValueMap.prename
                    lastname = keyValueMap.lastname
                }
            }
        }
        stage('Inform') {
            steps {
                echo "Pipeline build for ${prename} ${lastname}!"
            }
        }
    }
}
