pipeline {

    agent any

    environment {
        def prename = 'kein'
        def lastname = 'name'
    }
    
    stages {
        stage('Assign variables') {
            steps {
                script {
                    
                    def valuesFromFile = readFile 'C:/Users/FlorianEg/OneDrive - MaibornWolff GmbH/Desktop/values.txt'
                    def lines = valuesFromFile.split('\n')
                    def keyValueMap = [:]
        
                    lines.each { line ->
                        def keyValue = line.split(':')
                        if(keyValue.size() == 2){
                            def key = keyValue[0].trim()
                            def value = keyValue[1].trim()
                            keyValueMap[key] = value
                        }
                    }
                    env.prename = keyValueMap.prename
                    env.lastname = keyValueMap.lastname
                }
            }
        }
        stage('Inform') {
            steps {
                echo "Pipeline build for ${env.prename} ${env.lastname}!"
            }
        }
    }
}
