pipeline {

    agent any

    environment {
        def valuesFromFile = readFile './values.txt'
        def lines = valuesFromFile.split('\n')
    }
        def keyValueMap = [:]
    
        lines.each { line ->
            def keyValue = line.split(':')
            if(keyValue.size() == 2){
                def key = keyValue[0].trim()
                def value = keyValue[1].trim()
                keyValue[key] = value
            }
        }
    
        def prename = keyValueMap.prename
        def lastname = keyValueMap.lastname
    
    stages {
        stage('Build') {
            steps {
                sh 'mvn -B -DskipTests clean package'
            }
        }
        stage('Test') {
            steps {
                sh 'mvn test'
            }
        }
        stage('Deliver') {
            steps {
                sh './jenkins/scripts/deliver.sh'
            }
        }
        stage('Inform') {
            steps {
                echo 'Pipeline build for ${prename} ${lastname}!'
            }
        }
    }
}
